name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build
    - name: Set up Docker Build
      run: |
          docker --version 
          docker build -t angular-app:latest . 
    - name: Run Trivy Scan
      run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/trivy-cache:/root/.cache/trivy aquasec/trivy:latest image angular-app:latest



    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
