name: Angular CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t angular-app:latest .
        # docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-app:latest .
        # docker tag ${{ secrets.DOCKER_USERNAME }}/angular-app:latest ${{ secrets.DOCKER_USERNAME }}/angular-app:${{ github.sha }}

    # - name: Push Docker image
    #   run: |
    #     docker push ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
    #     docker push ${{ secrets.DOCKER_USERNAME }}/angular-app:${{ github.sha }}
